# Generated by Django 5.0.6 on 2024-06-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='change_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='涨跌幅'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='circulating_market_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='流通市值'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='code',
            field=models.CharField(default=600000, max_length=10, unique=True, verbose_name='股票代码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='gross_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='销售毛利率'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='industry',
            field=models.CharField(default=0, max_length=100, verbose_name='行业'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='latest_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最新价'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='name',
            field=models.CharField(default=0, max_length=100, verbose_name='名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='pe_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='市盈率-动态'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='roe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='净资产收益率'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='total_market_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='总市值'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['code'], name='stock_api_s_code_61ccd0_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['industry'], name='stock_api_s_industr_195808_idx'),
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='volume',
        ),
    ]
