# Generated by Django 5.0.6 on 2024-06-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0002_alter_stockdata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='行业'),
        ),
    ]
