# Generated by Django 5.0.6 on 2024-06-28 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0003_alter_stockdata_industry'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockdata',
            name='stock_api_s_industr_195808_idx',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='industry',
        ),
    ]
