# Generated by Django 5.0.6 on 2024-06-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0004_remove_stockdata_stock_api_s_industr_195808_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否在交易'),
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['is_active'], name='stock_api_s_is_acti_2748e0_idx'),
        ),
    ]
