# Generated by Django 5.0.6 on 2024-06-30 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0005_stockdata_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockdata',
            name='stock_api_s_is_acti_2748e0_idx',
        ),
    ]
