# Generated by Django 5.0.6 on 2024-07-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0007_stockinfo_stockspot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
