# Generated by Django 5.0.6 on 2024-07-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0008_stockinfo_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockspot',
            name='fund_shares_total_shares',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='总股本'),
        ),
        migrations.AlterField(
            model_name='stockspot',
            name='nav_market_cap',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='总市值'),
        ),
    ]
