# Generated by Django 5.0.6 on 2024-07-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0009_alter_stockspot_fund_shares_total_shares_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockspot',
            name='earnings_per_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='每股收益'),
        ),
        migrations.AlterField(
            model_name='stockspot',
            name='net_assets_per_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='每股净资产'),
        ),
        migrations.AlterField(
            model_name='stockspot',
            name='pb_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='市净率'),
        ),
        migrations.AlterField(
            model_name='stockspot',
            name='pe_ratio_dynamic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='市盈率(动)'),
        ),
        migrations.AlterField(
            model_name='stockspot',
            name='pe_ratio_static',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='市盈率(静)'),
        ),
        migrations.AlterField(
            model_name='stockspot',
            name='pe_ratio_ttm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='市盈率(TTM)'),
        ),
    ]
