# Generated by Django 5.0.6 on 2024-07-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0011_alter_stockspot_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockspot',
            name='turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='成交额'),
        ),
    ]
