# Generated by Django 5.0.6 on 2024-07-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0012_alter_stockspot_turnover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockspot',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='涨跌'),
        ),
        migrations.AlterField(
            model_name='stockspot',
            name='change_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='涨幅'),
        ),
        migrations.AlterField(
            model_name='stockspot',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='现价'),
        ),
        migrations.AlterField(
            model_name='stockspot',
            name='ytd_change_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='今年以来涨幅'),
        ),
    ]
