# Generated by Django 5.0.6 on 2024-10-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0013_alter_stockspot_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockspot',
            name='change_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='涨幅'),
        ),
        migrations.AlterField(
            model_name='stockspot',
            name='ytd_change_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='今年以来涨幅'),
        ),
    ]
